# Create subfolder within the current working directory

dir.create("Data")
dir.create("R")
dir.create("R/Global")
dir.create("R/Sites")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/Global")
dir.create("Output/Data/Global/csv")
dir.create("Output/Data/Global/excel")
dir.create("Output/Data/Sites")
dir.create("Output/Data/Sites/csv")
dir.create("Output/Data/Sites/excel")
dir.create("Output/Maps")
dir.create("Output/Maps/Global")
dir.create("Output/Maps/Sites")
dir.create("Output/Plots")
dir.create("Output/Plots/Global")
dir.create("Output/Plots/Sites")
dir.create("Output/Plots/Sites/Q-Q")
dir.create("Output/Plots/Sites/Residual")
dir.create("Output/Plots/Sites/ObsPred")
